name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # The workflow contains a single job called "release"
  release:
    # The runner will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define the steps run in the workflow
    steps:
      # Checkout out the code in the repository
      # Checkout the submodule for the bibliography
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: 'false'
      # Create a PDF using Playwright
      - name: Compile LaTeX document
        run: |
            npm install
            npm run export
      # Release a PDF of the presentation slides
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: slides-export.pdf
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
